name: docker build and deploy

on:
  push:
    branches: "master"

permissions:
      id-token: write
      contents: read

jobs:
  deploy-docker:
    runs-on: ubuntu-latest
    name: build and deploy

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        timeout-minutes: 1
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        timeout-minutes: 1
        uses: docker/setup-buildx-action@v2

      - name: Configure AWS credentials
        timeout-minutes: 5
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1

      - name: Login to Amazon ECR Public
        timeout-minutes: 5
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Build and push
        timeout-minutes: 30
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.login-ecr-public.outputs.registry }}/johang/sd-card-images:latest
