name: sd-card-images prebuilt

on:
  schedule:
    - cron: "00 12 * * 5"

jobs:
  test-prebuilt:
    runs-on: ubuntu-latest
    name: test ${{ matrix.debian }}

    strategy:
      matrix:
        include:
          # Debian armhf
          - boot: boot-qemu_arm_virt
            debian: debian-bullseye-armhf
          - boot: boot-qemu_arm_virt
            debian: debian-bookworm-armhf
          - boot: boot-qemu_arm_virt
            debian: debian-sid-armhf
          # Debian arm64
          - boot: boot-qemu_aarch64_virt
            debian: debian-bullseye-arm64
          - boot: boot-qemu_aarch64_virt
            debian: debian-bookworm-arm64
          - boot: boot-qemu_aarch64_virt
            debian: debian-sid-arm64
          # Ubuntu arm64
          - boot: boot-qemu_aarch64_virt
            debian: ubuntu-focal-arm64
          - boot: boot-qemu_aarch64_virt
            debian: ubuntu-jammy-arm64
      fail-fast: false

    env:
      BOOT: ${{ matrix.boot }}
      DEBIAN: ${{ matrix.debian }}

    steps:
    - name: Install dependencies
      timeout-minutes: 5
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get --assume-yes \
                     --no-install-recommends \
                     install pigz \
                             qemu-system-x86 \
                             qemu-system-arm \
                             ssh \
                             sshpass \
                             wget

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download
      timeout-minutes: 1
      env:
        BASE: https://ftp.sd-card-images.johang.se
      run: |
        wget $BASE/$(wget -O - $BASE/latest.txt | grep $BOOT || echo 404)
        wget $BASE/$(wget -O - $BASE/latest.txt | grep $DEBIAN || echo 404)

    - name: Test
      timeout-minutes: 5
      run: |
        ./test/qemu.sh $BOOT*.bin.gz $DEBIAN*.bin.gz
